services:
  frontend-release:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: runner
    ports:
      - "80:8080" # HTTP -> redirect
      - "443:8443" # HTTPS (host 443 -> container 8443)
    volumes:
      - ./frontend/ssl/localhost.pem:/etc/ssl/certs/fullchain.pem:ro
      - ./frontend/ssl/localhost-key.pem:/etc/ssl/private/privkey.pem:ro
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend-release
    restart: unless-stopped
    profiles: [ "release" ]

  frontend-debug:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: runner
    ports:
      - "80:8080" # HTTP -> redirect
      - "443:8443" # HTTPS (host 443 -> container 8443)
    volumes:
      - ./frontend/ssl/localhost.pem:/etc/ssl/certs/fullchain.pem:ro
      - ./frontend/ssl/localhost-key.pem:/etc/ssl/private/privkey.pem:ro
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend-debug
    restart: unless-stopped
    profiles: [ "debug" ]

  backend-release:
    build:
      context: ./backend/src
      args:
        - BUILD_CONFIGURATION=Release
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      - PFX_PATH=/var/ssl/private/localhost.pfx
    volumes:
      - ./backend/aspnet-keys:/keys
      - ./backend/localhost.pfx:/var/ssl/private/localhost.pfx:ro
    env_file: "backend/backend.env"
    restart: unless-stopped
    profiles: [ "release" ]

  backend-debug:
    build:
      context: ./backend/src
      args:
        - BUILD_CONFIGURATION=Debug
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      - PFX_PATH=/var/ssl/private/localhost.pfx
    volumes:
      - ./backend/aspnet-keys:/keys
      - ./backend/localhost.pfx:/var/ssl/private/localhost.pfx:ro
    env_file: "backend/backend.env"
    restart: unless-stopped
    profiles: [ "debug" ]

  postgres:
    image: postgres:17
    env_file: "db.env"
    ports:
      - "5434:5432"
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
