services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:8080"
    depends_on:
      - postgres
    volumes:
      - ./aspnet-keys:/keys
    env_file: "backend.env"
    restart: unless-stopped

  postgres:
    image: postgres:17
    env_file: "db.env"
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
