### GET all appointments
GET http://localhost:5000/api/Appointments

### Get appointment by id
GET http://localhost:5000/api/Appointments/6

### Create a new appointment
POST http://localhost:5000/api/Appointments
Content-Type: application/json
Accept: application/json

{
  "startTime": "2025-08-20T10:30:00Z",
  "durationInMinutes": 60,
  "type": "Diagnosis",
  "status": "Scheduled",
  "therapistId": 1,
  "patientId": -1
}

### Update an appointment
PATCH http://localhost:5000/api/Appointments/6
Content-Type: application/json
Accept: application/json

{
  "startTime": "2025-08-18T18:19:20.854Z",
  "durationInMinutes": 10,
  "type": "Diagnosis",
  "status": "NoShow",
  "patientId": 1
}

### Delete an appointment
DELETE http://localhost:5000/api/Appointments/5
